### ISSUE TITLE
lines and dots 

### ISSUE THREAD

**Issue by jorvlan** [ulyngs/simple-raincloud-plot#1]
Hey, I just came across this repo, 

I think you do know that the lines and dots are not connected? I guess to preserve the slope of the lines?
If not, then you might want to check the code again ;).

**Comment by ulyngs** [comment]
good point - fixed with ebe21f6, as per [this stackoverflow](https://stackoverflow.com/questions/57781581/lines-to-connect-geom-jitter-points-in-ggplot2).

Problem is that jittering in the dataframe itself can't be used to jitter horizontally on the categorical axis
